env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
db_server:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "root"
  db_name: "apm"
  db_path: "./db/db.sql"